export const LOADED_MOVIES = 'LOADED_MOVIES';
export const LOADED_MOVIES_SORT = 'LOADED_MOVIES_SORT';
export const LOADED_GENRES = 'LOADED_GENRES';
export const LOADED_CREDITS = 'LOADED_CREDITS';
export const LOADED_SEARCH_MOVIES = 'LOADED_SEARCH_MOVIES';
